### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by try1try** [Ebryx/AES-Killer#1]
Can you write a instruction book for it ？I am a small white，can't understand how use it.
Thanks

**Comment by d3vilbug** [comment]
yeah sure, working on it and will be sharing soon.
All you need to do is too extract SecretKey and Initialize parameter by reversing mobile which is being used by app for encryption/decryption
Just place secretkey and ivparameter in AES-Killer input fields and start AES-Killer and it will decrypt all you traffic on fly

**Comment by d3vilbug** [comment]
Hey @try1try  this will help you  https://github.com/Ebryx/AES-Killer/blob/master/README.md
