### ISSUE TITLE
Invalid AES key length

### ISSUE THREAD

**Issue by cyal1** [Ebryx/AES-Killer#11]
➜ echo UFlZUEBLRkBISEZa |base64
VUZsWlVFQkxSa0JJU0VaYQo=

do_decrypt :: Invalid AES key length: 17 bytes

**Comment by cyal1** [comment]
requests need urlencode/decode and response do not need  urlencode/decode in some  cases

**Comment by d3vilbug** [comment]
> ➜ echo UFlZUEBLRkBISEZa |base64
> VUZsWlVFQkxSa0JJU0VaYQo=
> 
> do_decrypt :: Invalid AES key length: 17 bytes

key is not correct in this case

**Comment by d3vilbug** [comment]
> requests need urlencode/decode and response do not need urlencode/decode in some cases

you have to customize the current code for that
