### ISSUE TITLE
Other situation

### ISSUE THREAD

**Issue by la0s** [Ebryx/AES-Killer#2]
Can we add support for url encode, like data=P9%2bN0gB8z3do2u97LIO%2fJuo, it seems that it can't be decrypted, and support for original hexadecimal data after encryption (not base64)，thanks！

**Comment by d3vilbug** [comment]
Can you please elaborate more??
What my understanding is
- First data is encrypted
- Then URL_encode(encrypted_data) which change/convert `+` to `%2b` and `/`  to `%2f`

If this is the case **i will add URL_encode/decode option** in this plugin. Meanwhile you can make it work with Obfuscation option
what you need to do is 
- in `Off. char` field place these values which gets url encoded separated with space like `+ /`
- in `Replace with` field place their URL encoded values separated with space `%2b %2f`

So before decrypting request/response code will first replace URL encoded char with original ones, then decrypt your url decoded data and vise versa for encryption 

Hope this might help you right now 😈

**Comment by la0s** [comment]
Wow, thank you for your detailed and patient response. yes, you understand is right. I have encountered a lot of apps,after the final encryption then  do urlencode . like the picture below  
![image](https://user-images.githubusercontent.com/37521845/48005019-55062e80-e14d-11e8-9491-ea6ce0e4676c.png)
The second case I want to say，some apps may not do base64, they will use  original hex encrypted data,I hope you can think about it.Thanks  
![image](https://user-images.githubusercontent.com/37521845/48005514-9ba85880-e14e-11e8-9924-ec7c3994bde0.png)

**Comment by d3vilbug** [comment]
Thanks @la0s  for suggestion. Sure i will look into it and update you soon.

**Comment by ducnp** [comment]
Hi @la0s how you set Request/Response parameter to decrypt JSON format ? I'm stucking in this scenario. Thanks for your help

**Comment by d3vilbug** [comment]
Added few variants for such challenges and can be modified easily 

https://github.com/Ebryx/AES-Killer#variants
