### ISSUE TITLE
Can this tool encrypt and decrypt packets in json format?

### ISSUE THREAD

**Issue by Shadow2chery** [Ebryx/AES-Killer#3]
Can this tool encrypt and decrypt packets in json format?

**Comment by d3vilbug** [comment]
@FortuneC00kie  can you share example screenshot ???

**Comment by Shadow2chery** [comment]
![image](https://user-images.githubusercontent.com/26539482/48683949-76095d80-ebea-11e8-8250-ebaca5406146.png)

**Comment by d3vilbug** [comment]
Thanks i get it. For now it will not work with this request.
For such Scenario i am adding `Request/Response Parameter` in this plugin this week.

**Comment by davidryanorg** [comment]
Quite often you can have multiple parameters in the JSON, so it would be good to be able to specify which one contains the encrypted data.

**Comment by d3vilbug** [comment]
Actually i have update the plugin for such cases but i need app to test test its functionality and fix bug if any.
Would you mind sharing such app ???

**Comment by mmrvega** [comment]
can u make a listener for json i think the encryption is inside the javascript  like this
![image](https://user-images.githubusercontent.com/13336891/52248156-1de71b00-28fe-11e9-8945-8eb5391eb7ec.png)
i'm not sure if it was a aes secret key
but i can give u the server to test it in
and if u want send me a message to my instagram @mmr_vega and we will make it together ...

**Comment by ducnp** [comment]
Hi @d3vilbug : Do you have an update for this issue? I'm also stucking with JSON requests. Thanks you so much !

**Comment by d3vilbug** [comment]
Hi @ducnp @FortuneC00kie 

I know its a bit late ..... but here is the JSON Variant https://gist.github.com/d3vilbug/853d6823a015cfe20656bd24ad8dd410

**Comment by d3vilbug** [comment]
> Quite often you can have multiple parameters in the JSON, so it would be good to be able to specify which one contains the encrypted data.

Hi @davidryanorg 

you can specify parameter and endpoints is this variant https://gist.github.com/d3vilbug/391cc26b27de37e49f5e75682f65ed5b
