### ISSUE TITLE
how can find IV if application secure coding

### ISSUE THREAD

**Issue by bypazs** [Ebryx/AES-Killer#5]
Hello, In my case found only _Secret Key_ Is possible to find IV if the application secure coding.

**Comment by d3vilbug** [comment]
Hi,

You can hook the init method too to get Secret Key, IV and original data before encryption
https://11x256.github.io/Frida-hooking-android-part-5/

On the other hand, Brida our friend can fetch everything for you. 
https://github.com/federicodotta/Brida
