### ISSUE TITLE
no main manifest attribute, in AES_Killer.jar

### ISSUE THREAD

**Issue by ashraful1980** [Ebryx/AES-Killer#6]
Sir,
I have error massage as following: no main manifest attribute, in AES_Killer.jar. Please advice....

![error](https://user-images.githubusercontent.com/52574658/89570040-6b23b000-d847-11ea-902b-b9e81af0e9ec.jpg)

**Comment by d3vilbug** [comment]
Hi @ashraful1980 ,

you need to use this as Burp Plugin because burp plugins can't run standalone. Please the step as shown in the GIF

**Comment by d3vilbug** [comment]
OR can refer to this section https://github.com/Ebryx/AES-Killer#how-to-install
