### ISSUE TITLE
Decryption of SHA-512 iterations

### ISSUE THREAD

**Issue by ashraful1980** [Ebryx/AES-Killer#7]
Dear Sir,
I could not understand how to decrypt following hash; could you please help me to learn the decryption for your AES-Killer  software. As bellow information collect from gurnec/btcrecover - GitHub.

Partial Bitcoin Core encrypted master key, salt, iter_count, and crc in base64: 
Wallet difficulty: 191,354 SHA-512 iterations
YmM6b+q1Ayn54BVFdreDdkg/4LoNdYiRbzuQLundXcJL7w4b2m7KUXzCFdU7AQBlRG0B | base64 -d

**Comment by d3vilbug** [comment]
Hi @ashraful1980 

I am afraid that AES Killer can't help you in this regard.
