### ISSUE TITLE
Base64 Support

### ISSUE THREAD

**Issue by aress31** [Ebryx/AES-Killer#8]
Could you please consider implementing support for base64 encoded AES keys and content?

**Comment by d3vilbug** [comment]
Hi @aress31 

You can try AES_Killer_v3.0 https://github.com/Ebryx/AES-Killer/blob/master/README.md#variants otherwise will update UI with this new version too

**Comment by d3vilbug** [comment]
Hi @aress31 

It is implemented in lastest build.
